FROM <registry name>.azurecr.io/angular:5.0.1

# Change directory so that our commands run inside this new directory
WORKDIR /app

# Get all the code needed to run the app
COPY . /app

# Expose the port the app runs in
EXPOSE 4321